---
- name: Install development packages
  include: devpackages.yml
  when: install_development_packages

- name: Activate virtualenv on user Login
  include: venv.yml
  when: virtualenv_on_login

- name: Install ZSH and Oh My ZSH
  include: zsh.yml
  when: use_zsh
