---

- include: ../../../common/handlers/supervisor_service.yml
           role=dbserver
           service_name=postgresql
           supervisor_name=postgresql

#
# Need to have users and DB setup after service is actually started, so we put
# it in handlers.
#
- name: ensure PostgreSQL user
  postgresql_user: name={{ settings_dbuser }}
                   password={{ settings_dbpassword }}
                   login_host=/tmp
                   state=present
  sudo_user: postgres

- name: ensure PostgreSQL db
  postgresql_db: db={{ settings_dbname }}
                 owner={{ settings_dbuser }}
                 login_host=/tmp
                 encoding='UTF-8'
                 lc_collate='en_US.utf8'
                 lc_ctype='en_US.utf8'
                 template=template0
                 state=present
  sudo_user: postgres

- include: ../../../common/handlers/supervisor_service.yml
           role=dbserver
           service_name=pgbouncer
           supervisor_name=pgbouncer
