---
- name: install Gunicorn
  pip: name=gunicorn version={{ gunicorn_version }} virtualenv={{ virtualenv_dir }}

- name: dummy task for gunicorn tasks when code changed
  command: /bin/true
  notify:
    - restart gunicorn
    - run collectstatic

- include: ../../../common/tasks/supervisor_service.yml
           service_type=non-apt
           role=gunicorn
           service_name=gunicorn
           supervisor_name=gunicorn
