---
- name: configuration check
  hosts: localhost
  tasks:
    - name: project settings check (1/2)
      fail: msg="Make sure project_name and secret_key are correctly defined"
      when: project_name|default('') == '' or secret_key|default('') == ''

    - name: project settings check (2/2)
      fail: msg="Make sure the project is either created or the repo pulled"
      when: not (pull_repo and repo_url) and not create_project


# Used for creating AMI's in Packer
- name: Metamon local provision
  sudo: yes
  hosts: localhost
  vars_files:
    - group_vars/all.yml
  roles:
    - dbserver
    - gunicorn
    - nginx
    - development
    - testing
