---
- name: system-wide install of virtualenv and virtualenvwrapper
  pip: name={{ item }} state=present
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: Modify bashrc for virtualenvwrapper (1/2)
  lineinfile: dest={{ home }}/.profile
              regexp="^export WORKON_HOME"
              line="export WORKON_HOME=$HOME/.virtualenvs"
              state=present

- name: Modify bashrc for virtualenvwrapper (2/2)
  lineinfile: dest={{ home }}/.profile
              regexp="^source /usr/local/bin/virtualenvwrapper.sh"
              line="source /usr/local/bin/virtualenvwrapper.sh"
              state=present
